Name: product.rpc
ListenOn: 127.0.0.1:8081
Mode: dev
Etcd:
  Hosts:
  - 127.0.0.1:2379
  Key: product.rpc
DataSource: root:lxq123456@tcp(120.24.250.172:3306)/product?parseTime=true
CacheRedis:
  - Host: 127.0.0.1:6379
    Pass:
    Type: node

